"use client";

import React, { useState } from 'react';
import Link from 'next/link';
import ThemeToggle from '../../../components/theme-toggle';

type Article = {
  id: string;
  topic: string;
  status: 'pending' | 'generating' | 'completed' | 'failed';
  progress: number;
  createdAt: string;
  content: string;
};

type GenerationSettings = {
  maxConvTurn: number;
  maxPerspective: number;
  searchTopK: number;
  maxSearchQueries: number;
};

const generateArticleContent = (topic: string): string => {
  return `# ${topic}

## Introduction

This comprehensive article explores ${topic} from multiple perspectives, synthesizing information from various authoritative sources to provide a complete understanding of the subject matter.

## Background

${topic} has become increasingly important in recent years. Understanding its fundamental concepts is essential for anyone looking to gain expertise in this area.

### Historical Context

The development of ${topic} can be traced back to key innovations and discoveries that shaped our current understanding. Researchers and practitioners have contributed significantly to advancing this field.

## Key Concepts

### Core Principles

1. **Foundation**: The basic principles that underpin ${topic}
2. **Applications**: Real-world use cases and implementations
3. **Best Practices**: Recommended approaches for working with ${topic}

### Technical Details

When examining ${topic} more closely, several technical aspects emerge as particularly important:

- Theoretical frameworks that guide implementation
- Practical considerations for deployment
- Common challenges and their solutions

## Current State and Future Directions

The field continues to evolve rapidly, with new developments emerging regularly. Experts predict significant advancements in the coming years.

## Conclusion

${topic} represents a fascinating and important area of study. This article has provided an overview of the key concepts, historical context, and current state of the field.

---

*Generated by Sidekick AI - Vale Technologies*

**References:**
1. Academic sources and research papers
2. Industry publications and reports
3. Expert interviews and analyses`;
};

export default function SidekickGeneratePage() {
  const [topic, setTopic] = useState('');
  const [showAdvanced, setShowAdvanced] = useState(false);
  const [settings, setSettings] = useState<GenerationSettings>({
    maxConvTurn: 3,
    maxPerspective: 3,
    searchTopK: 5,
    maxSearchQueries: 3,
  });
  const [isGenerating, setIsGenerating] = useState(false);
  const [currentArticle, setCurrentArticle] = useState<Article | null>(null);
  const [selectedArticle, setSelectedArticle] = useState<Article | null>(null);
  const [articles, setArticles] = useState<Article[]>([
    { 
      id: '1', 
      topic: 'Introduction to Artificial Intelligence', 
      status: 'completed', 
      progress: 100, 
      createdAt: '2025-01-15',
      content: generateArticleContent('Introduction to Artificial Intelligence')
    },
    { 
      id: '2', 
      topic: 'Machine Learning Basics', 
      status: 'completed', 
      progress: 100, 
      createdAt: '2025-01-14',
      content: generateArticleContent('Machine Learning Basics')
    },
  ]);

  const handleGenerate = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!topic.trim()) return;

    setIsGenerating(true);
    const newArticle: Article = {
      id: Date.now().toString(),
      topic,
      status: 'generating',
      progress: 0,
      createdAt: new Date().toISOString().split('T')[0],
      content: '',
    };
    setCurrentArticle(newArticle);

    let progress = 0;

    const interval = setInterval(() => {
      progress += Math.random() * 15 + 5;
      if (progress >= 100) {
        progress = 100;
        clearInterval(interval);
        const completedArticle: Article = { 
          ...newArticle, 
          status: 'completed', 
          progress: 100,
          content: generateArticleContent(topic)
        };
        setArticles(prev => [completedArticle, ...prev]);
        setCurrentArticle(null);
        setIsGenerating(false);
        setTopic('');
      } else {
        setCurrentArticle(prev => prev ? { ...prev, progress: Math.min(progress, 99) } : null);
      }
    }, 800);
  };

  const handleViewArticle = (article: Article) => {
    if (article.status === 'completed') {
      setSelectedArticle(article);
    }
  };

  const handleCloseArticle = () => {
    setSelectedArticle(null);
  };

  const getProgressStage = (progress: number): string => {
    if (progress < 25) return 'Researching topic from multiple perspectives...';
    if (progress < 50) return 'Generating comprehensive outline...';
    if (progress < 75) return 'Writing article sections...';
    return 'Polishing and adding citations...';
  };

  return (
    <div style={{ 
      minHeight: '100vh', 
      background: 'var(--background)', 
      color: 'rgba(255,255,255,0.9)', 
      fontFamily: "'Poppins', sans-serif", 
      padding: '2rem' 
    }}>
      <style>{`
        @import url('https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap');
        
        :root {
          --primary-color: #8b5cf6;
          --text-color: rgba(255,255,255,0.9);
          --background: linear-gradient(135deg, #1e3c72 0%, #2a5298 100%);
        }

        [data-theme="dark"] {
          --primary-color: #a78bfa;
          --background: linear-gradient(135deg, #0f172a 0%, #1e293b 100%);
        }
        
        .generate-container { max-width: 1000px; margin: 0 auto; }
        .back-link { color: rgba(255,255,255,0.8); text-decoration: none; display: inline-flex; align-items: center; gap: 0.5rem; margin-bottom: 2rem; transition: color 0.3s; }
        .back-link:hover { color: white; }
        .page-title { font-size: 2.5rem; margin-bottom: 0.5rem; background: linear-gradient(135deg, #8b5cf6, #7c3aed); -webkit-background-clip: text; -webkit-text-fill-color: transparent; }
        .page-subtitle { color: rgba(255,255,255,0.7); margin-bottom: 2rem; font-size: 1.1rem; }
        
        .card { background: rgba(255,255,255,0.05); backdrop-filter: blur(15px); border-radius: 25px; padding: 2rem; border: 1px solid rgba(255,255,255,0.1); margin-bottom: 2rem; }
        .card-title { font-size: 1.5rem; font-weight: 600; color: white; margin-bottom: 1.5rem; }
        
        .form-group { margin-bottom: 1.5rem; }
        .form-label { display: block; color: rgba(255,255,255,0.9); font-weight: 500; margin-bottom: 0.5rem; font-size: 0.95rem; }
        .form-input { width: 100%; padding: 1rem 1.25rem; background: rgba(255,255,255,0.08); border: 2px solid rgba(255,255,255,0.1); border-radius: 15px; color: white; font-size: 1rem; transition: all 0.3s ease; font-family: inherit; }
        .form-input:focus { outline: none; border-color: #8b5cf6; background: rgba(255,255,255,0.1); }
        .form-input::placeholder { color: rgba(255,255,255,0.4); }
        
        .advanced-toggle { display: flex; align-items: center; gap: 0.5rem; color: rgba(255,255,255,0.8); cursor: pointer; margin-bottom: 1rem; font-weight: 500; transition: color 0.3s; }
        .advanced-toggle:hover { color: white; }
        .advanced-content { display: grid; grid-template-columns: repeat(2, 1fr); gap: 1rem; margin-bottom: 1.5rem; padding: 1.5rem; background: rgba(255,255,255,0.03); border-radius: 15px; }
        .form-input-sm { padding: 0.75rem 1rem; }
        
        .btn-generate { width: 100%; padding: 1rem 2rem; background: linear-gradient(135deg, #8b5cf6, #7c3aed); color: white; border: none; border-radius: 15px; font-size: 1rem; font-weight: 600; cursor: pointer; transition: all 0.3s ease; display: flex; align-items: center; justify-content: center; gap: 0.5rem; font-family: inherit; }
        .btn-generate:hover:not(:disabled) { transform: translateY(-2px); box-shadow: 0 10px 30px rgba(139, 92, 246, 0.4); }
        .btn-generate:disabled { opacity: 0.7; cursor: not-allowed; transform: none; }
        
        .progress-section { margin-bottom: 1rem; }
        .progress-header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 0.5rem; color: rgba(255,255,255,0.8); font-size: 0.9rem; }
        .progress-bar-container { height: 8px; background: rgba(255,255,255,0.1); border-radius: 10px; overflow: hidden; }
        .progress-bar { height: 100%; background: linear-gradient(135deg, #8b5cf6, #7c3aed); border-radius: 10px; transition: width 0.5s ease; }
        
        .progress-steps { margin-top: 1rem; }
        .progress-step { display: flex; align-items: center; gap: 0.5rem; padding: 0.5rem 0; color: rgba(255,255,255,0.6); font-size: 0.9rem; }
        .progress-step.active { color: rgba(255,255,255,0.9); }
        .progress-step.completed { color: #10b981; }
        
        .articles-list { }
        .article-item { display: flex; justify-content: space-between; align-items: center; padding: 1.25rem; background: rgba(255,255,255,0.03); border-radius: 15px; margin-bottom: 0.75rem; transition: all 0.3s ease; cursor: pointer; }
        .article-item:hover { background: rgba(255,255,255,0.08); }
        .article-info { flex: 1; }
        .article-topic { font-weight: 600; color: white; margin-bottom: 0.25rem; }
        .article-date { font-size: 0.85rem; color: rgba(255,255,255,0.5); }
        .article-status { padding: 0.4rem 1rem; border-radius: 20px; font-size: 0.8rem; font-weight: 600; }
        .status-completed { background: rgba(16, 185, 129, 0.2); color: #10b981; }
        .status-generating { background: rgba(139, 92, 246, 0.2); color: #a78bfa; }
        .status-failed { background: rgba(239, 68, 68, 0.2); color: #ef4444; }
        
        .empty-state { text-align: center; padding: 3rem; color: rgba(255,255,255,0.5); }
        
        .spinner { animation: spin 1s linear infinite; }
        @keyframes spin { from { transform: rotate(0deg); } to { transform: rotate(360deg); } }
        
        .article-modal-overlay { position: fixed; top: 0; left: 0; right: 0; bottom: 0; background: rgba(0,0,0,0.8); backdrop-filter: blur(10px); z-index: 1000; display: flex; align-items: center; justify-content: center; padding: 2rem; }
        .article-modal { background: linear-gradient(135deg, #1e3c72 0%, #2a5298 100%); border-radius: 25px; max-width: 900px; width: 100%; max-height: 90vh; overflow: hidden; border: 1px solid rgba(255,255,255,0.2); box-shadow: 0 25px 50px rgba(0,0,0,0.5); }
        .article-modal-header { display: flex; justify-content: space-between; align-items: center; padding: 1.5rem 2rem; border-bottom: 1px solid rgba(255,255,255,0.1); background: rgba(255,255,255,0.05); }
        .article-modal-title { font-size: 1.3rem; font-weight: 600; color: white; margin: 0; }
        .article-modal-close { background: rgba(255,255,255,0.1); border: none; color: white; width: 40px; height: 40px; border-radius: 10px; cursor: pointer; font-size: 1.5rem; display: flex; align-items: center; justify-content: center; transition: all 0.3s ease; }
        .article-modal-close:hover { background: rgba(255,255,255,0.2); transform: scale(1.1); }
        .article-modal-content { padding: 2rem; overflow-y: auto; max-height: calc(90vh - 80px); }
        .article-content { color: rgba(255,255,255,0.9); line-height: 1.8; }
        .article-content h1 { font-size: 2rem; margin-bottom: 1.5rem; color: white; background: linear-gradient(135deg, #8b5cf6, #7c3aed); -webkit-background-clip: text; -webkit-text-fill-color: transparent; }
        .article-content h2 { font-size: 1.5rem; margin: 2rem 0 1rem; color: white; border-bottom: 1px solid rgba(255,255,255,0.1); padding-bottom: 0.5rem; }
        .article-content h3 { font-size: 1.2rem; margin: 1.5rem 0 0.75rem; color: rgba(255,255,255,0.95); }
        .article-content p { margin-bottom: 1rem; }
        .article-content ul, .article-content ol { margin-bottom: 1rem; padding-left: 1.5rem; }
        .article-content li { margin-bottom: 0.5rem; }
        .article-content strong { color: #a78bfa; }
        .article-content hr { border: none; border-top: 1px solid rgba(255,255,255,0.1); margin: 2rem 0; }
        .article-content em { color: rgba(255,255,255,0.7); }
        
        @media (max-width: 768px) {
          .page-title { font-size: 1.8rem; }
          .advanced-content { grid-template-columns: 1fr; }
          .article-item { flex-direction: column; align-items: flex-start; gap: 0.75rem; }
          .article-modal { margin: 1rem; max-height: 95vh; }
          .article-modal-content { padding: 1.5rem; }
        }
      `}</style>
      
      <div className="generate-container">
        <Link href="/sidekick" className="back-link">
          ← Back to Sidekick
        </Link>
        
        <ThemeToggle />
        
        <h1 className="page-title">Sidekick Article Generator</h1>
        <p className="page-subtitle">Generate comprehensive, Wikipedia-style articles with citations</p>

        {/* Generation Form */}
        <div className="card">
          <h2 className="card-title">Start New Article</h2>
          
          <form onSubmit={handleGenerate}>
            <div className="form-group">
              <label className="form-label">Article Topic *</label>
              <input 
                type="text"
                className="form-input"
                placeholder="e.g., Quantum Computing, Ancient Rome, Machine Learning"
                value={topic}
                onChange={(e) => setTopic(e.target.value)}
                required
                disabled={isGenerating}
              />
            </div>

            <div 
              className="advanced-toggle" 
              onClick={() => setShowAdvanced(!showAdvanced)}
            >
              <span>{showAdvanced ? '▼' : '▶'}</span>
              <span>Advanced Options</span>
            </div>

            {showAdvanced && (
              <div className="advanced-content">
                <div className="form-group" style={{ marginBottom: 0 }}>
                  <label className="form-label">Max Conversation Turns</label>
                  <input 
                    type="number"
                    className="form-input form-input-sm"
                    value={settings.maxConvTurn}
                    onChange={(e) => setSettings({ ...settings, maxConvTurn: parseInt(e.target.value) || 3 })}
                    min={1}
                    max={10}
                  />
                </div>
                <div className="form-group" style={{ marginBottom: 0 }}>
                  <label className="form-label">Max Perspectives</label>
                  <input 
                    type="number"
                    className="form-input form-input-sm"
                    value={settings.maxPerspective}
                    onChange={(e) => setSettings({ ...settings, maxPerspective: parseInt(e.target.value) || 3 })}
                    min={1}
                    max={10}
                  />
                </div>
                <div className="form-group" style={{ marginBottom: 0 }}>
                  <label className="form-label">Search Results per Query</label>
                  <input 
                    type="number"
                    className="form-input form-input-sm"
                    value={settings.searchTopK}
                    onChange={(e) => setSettings({ ...settings, searchTopK: parseInt(e.target.value) || 5 })}
                    min={1}
                    max={20}
                  />
                </div>
                <div className="form-group" style={{ marginBottom: 0 }}>
                  <label className="form-label">Max Search Queries</label>
                  <input 
                    type="number"
                    className="form-input form-input-sm"
                    value={settings.maxSearchQueries}
                    onChange={(e) => setSettings({ ...settings, maxSearchQueries: parseInt(e.target.value) || 3 })}
                    min={1}
                    max={10}
                  />
                </div>
              </div>
            )}

            <button 
              type="submit" 
              className="btn-generate"
              disabled={isGenerating || !topic.trim()}
            >
              {isGenerating ? (
                <>
                  <svg className="spinner" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                    <circle cx="12" cy="12" r="10" strokeOpacity="0.25" />
                    <path d="M12 2a10 10 0 0 1 10 10" />
                  </svg>
                  Generating...
                </>
              ) : (
                <>📝 Generate Article</>
              )}
            </button>
          </form>
        </div>

        {/* Progress Tracker */}
        {currentArticle && (
          <div className="card">
            <h3 className="card-title">Generating: {currentArticle.topic}</h3>
            
            <div className="progress-section">
              <div className="progress-header">
                <span>{getProgressStage(currentArticle.progress)}</span>
                <span>{Math.round(currentArticle.progress)}%</span>
              </div>
              <div className="progress-bar-container">
                <div className="progress-bar" style={{ width: `${currentArticle.progress}%` }}></div>
              </div>
            </div>

            <div className="progress-steps">
              <div className={`progress-step ${currentArticle.progress >= 25 ? 'completed' : currentArticle.progress > 0 ? 'active' : ''}`}>
                {currentArticle.progress >= 25 ? '✓' : '○'} Researching topic from multiple perspectives
              </div>
              <div className={`progress-step ${currentArticle.progress >= 50 ? 'completed' : currentArticle.progress >= 25 ? 'active' : ''}`}>
                {currentArticle.progress >= 50 ? '✓' : '○'} Generating comprehensive outline
              </div>
              <div className={`progress-step ${currentArticle.progress >= 75 ? 'completed' : currentArticle.progress >= 50 ? 'active' : ''}`}>
                {currentArticle.progress >= 75 ? '✓' : '○'} Writing article sections
              </div>
              <div className={`progress-step ${currentArticle.progress >= 100 ? 'completed' : currentArticle.progress >= 75 ? 'active' : ''}`}>
                {currentArticle.progress >= 100 ? '✓' : '○'} Polishing and adding citations
              </div>
            </div>
          </div>
        )}

        {/* Articles List */}
        <div className="card">
          <h2 className="card-title">Generated Articles</h2>
          
          <div className="articles-list">
            {articles.length > 0 ? (
              articles.map((article) => (
                <div 
                  key={article.id} 
                  className="article-item"
                  onClick={() => handleViewArticle(article)}
                  style={{ cursor: article.status === 'completed' ? 'pointer' : 'default' }}
                >
                  <div className="article-info">
                    <div className="article-topic">{article.topic}</div>
                    <div className="article-date">{article.createdAt}</div>
                  </div>
                  <span className={`article-status status-${article.status}`}>
                    {article.status === 'completed' ? 'View Article →' : article.status}
                  </span>
                </div>
              ))
            ) : (
              <div className="empty-state">
                No articles generated yet. Start by entering a topic above!
              </div>
            )}
          </div>
        </div>
      </div>

      {/* Article View Modal */}
      {selectedArticle && (
        <div className="article-modal-overlay" onClick={handleCloseArticle}>
          <div className="article-modal" onClick={(e) => e.stopPropagation()}>
            <div className="article-modal-header">
              <h2 className="article-modal-title">{selectedArticle.topic}</h2>
              <button className="article-modal-close" onClick={handleCloseArticle}>
                ×
              </button>
            </div>
            <div className="article-modal-content">
              <div className="article-content">
                {selectedArticle.content.split('\n').map((line, index) => {
                  if (line.startsWith('# ')) {
                    return <h1 key={index}>{line.substring(2)}</h1>;
                  } else if (line.startsWith('## ')) {
                    return <h2 key={index}>{line.substring(3)}</h2>;
                  } else if (line.startsWith('### ')) {
                    return <h3 key={index}>{line.substring(4)}</h3>;
                  } else if (line.startsWith('- ')) {
                    return <li key={index}>{line.substring(2)}</li>;
                  } else if (line.match(/^\d+\. \*\*/)) {
                    const content = line.replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>');
                    return <li key={index} dangerouslySetInnerHTML={{ __html: content }} />;
                  } else if (line.startsWith('---')) {
                    return <hr key={index} />;
                  } else if (line.startsWith('*') && line.endsWith('*') && !line.startsWith('**')) {
                    return <p key={index}><em>{line.slice(1, -1)}</em></p>;
                  } else if (line.trim() === '') {
                    return <br key={index} />;
                  } else {
                    const content = line
                      .replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>')
                      .replace(/\*([^*]+)\*/g, '<em>$1</em>');
                    return <p key={index} dangerouslySetInnerHTML={{ __html: content }} />;
                  }
                })}
              </div>
            </div>
          </div>
        </div>
      )}
      
      <link rel="stylesheet" href="https://unicons.iconscout.com/release/v4.0.8/css/line.css" />
    </div>
  );
}
